# Generated by Django 3.0.6 on 2020-05-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
