# Generated by Django 3.0.6 on 2020-05-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Status',
        ),
    ]
