# Generated by Django 3.0.6 on 2020-05-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0004_auto_20200511_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
