# Generated by Django 3.0.6 on 2020-05-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prismo', '0006_auto_20200511_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'profile_image'),
        ),
        migrations.DeleteModel(
            name='Profile_Image',
        ),
    ]
